StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 200

MethodLength:
  Max: 25

AllCops:
  RunRailsCops: true
  Exclude:
    - db/**/*
    - vendor/**/*
    - bin/*
    - Guardfile
    - config/unicorn.rb
